feat: add `import-deno` as crate feature to import using `.ts` extension
Aleph-Alpha/ts-rs pull request #376
Opened 2024-12-17 22:09 UTC by eythaann

## Goal
Allow to generate files compatible with Deno projects.

## Changes
I added a new feature `import-deno` works identically as `import-esm` but instead of import using `.js` Deno uses `.ts`

## Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/Aleph-Alpha/ts-rs/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2024-12-27 11:57 UTC, gustavo-shigueo commented on ts-rs/src/export.rs
The `is_same_file` check in lines 312-318 fails when using `import-deno` due to the `trim_end_matches(".ts")` in line 315, this line now needs to check if the feature flag is active

2024-12-27 11:59 UTC, gustavo-shigueo requested changes
The `--all-features` test is failing due to the `trim_end_matches` problem mentioned above

2025-01-19 00:51 UTC, eythaann commented
Fixed, just to note, I'm not able to run `npx tsc` like there's no package.json on the project.

2025-01-21 01:33 UTC, gustavo-shigueo approved these changes
Thanks for the fix! @NyxCode is there anything you'd like to add?

2025-02-22 10:19 UTC, eythaann commented
. (little point to not be forgotten)

2025-06-29 14:47 UTC, gustavo-shigueo commented
Now that I think about it, of course `--all-features` fails, it enables both this feature and `import-esm`.

I kinda feel like implementing `import-esm` was a mistake from my part, given that there is no point... By the time JavaScript could possibly care about ESM imiports, the offending files would be gone, due to them being only type definitions, which JS doesn't care about. Still, maybe there's something I'm not considering, like maybe the TS compiler checks for this, so we can't just remove it.

Though I think there may be a better alternative: Replace both features by an attribute, something like `import_extension = ".js"` and `import_extension = ".ts"`. This would even help with a concern that @NyxCode originally raised during the implementation of `import-esm` (https://github.com/Aleph-Alpha/ts-rs/pull/192#issuecomment-1902164456)

I'd like some input on this subject though, maybe it'd be a good idea to open an issue/discussioin about it

2025-06-29 15:11 UTC, gustavo-shigueo commented
For now, to make the tests pass, what you should do is this:

- in your test file, use `#![cfg(all(feature = "import-deno", not(feature = "import-esm")))]`
- in the import-esm test file, use `#![cfg(all(feature = "import-esm", not(feature = "import-deno")))]`
- in the CI script, add two jobs, one that runs `cargo test --features import-deno` and one that runs `cargo test --features import-esm`

2025-08-19 22:12 UTC, closed without merging